from . import crfp_shipment
from . import crfp_shipment_line
from . import crfp_shipment_container
from . import crfp_shipment_booking
from . import crfp_shipment_document
from . import crfp_shipment_checklist
from . import crfp_shipment_alert
from . import crfp_shipment_log
from . import crfp_checklist_template
from . import crfp_document_type
from . import crfp_tracking_event
from . import crfp_tracking_position
from . import crfp_tracking_temperature
from . import crfp_container_config
from . import crfp_container_config_line
from . import crfp_shipment_portal
from . import sale_order
from . import account_move
from . import account_move_line
