from odoo import models, fields, api


class CrfpShipmentDocument(models.Model):
    _name = 'crfp.shipment.document'
    _description = 'Shipment Document'
    _order = 'date_required, id'

    shipment_id = fields.Many2one('crfp.shipment', required=True, ondelete='cascade')

    doc_type = fields.Selection([
        ('booking_request', 'Booking Request'),
        ('booking_confirmation', 'Booking Confirmation'),
        ('shipping_instructions', 'Shipping Instructions'),
        ('packing_list', 'Packing List'),
        ('commercial_invoice', 'Commercial Invoice'),
        ('bl_draft', 'BL Draft'),
        ('bl_original', 'BL Original'),
        ('phytosanitary', 'Phytosanitary Certificate'),
        ('cert_origin', 'Certificate of Origin'),
        ('insurance', 'Insurance Document'),
        ('fumigation', 'Fumigation Certificate'),
        ('temperature_record', 'Temperature Record'),
        ('customs_declaration', 'Customs Declaration'),
        ('delivery_note', 'Delivery Note'),
        ('customer_copy', 'Customer Document Package'),
        ('vgm_verification', 'VGM Verification'),
        ('eur1', 'EUR.1 Movement Certificate'),
        ('bl_correction', 'BL Correction Request'),
        ('other', 'Other'),
    ], string='Document Type', required=True)

    doc_source = fields.Selection([
        ('generated', 'Generated by CR Farm'),
        ('received', 'Received from Third Party'),
        ('odoo_ref', 'Reference to Odoo Document'),
        ('control', 'Control / Checklist Only'),
    ], string='Source', required=True, default='received')

    state = fields.Selection([
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('ready', 'Ready'),
        ('sent', 'Sent'),
        ('received', 'Received'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
        ('na', 'N/A'),
    ], string='Status', default='pending')

    is_required = fields.Boolean(string='Required', default=True)
    reference = fields.Char(string='Reference Number')
    date_required = fields.Date(string='Deadline')
    date_ready = fields.Date(string='Date Ready')
    date_sent = fields.Date(string='Date Sent')
    date_received = fields.Date(string='Date Received')
    date_approved = fields.Date(string='Date Approved')
    responsible_id = fields.Many2one('res.users', string='Responsible')
    partner_id = fields.Many2one('res.partner', string='Sent to / Received from')

    # Reference to Odoo invoice (for doc_source = odoo_ref)
    account_move_id = fields.Many2one('account.move', string='Odoo Invoice/Document')

    # Attachments via M2M (not Binary)
    attachment_ids = fields.Many2many('ir.attachment', string='Attachments')

    is_overdue = fields.Boolean(compute='_compute_is_overdue', store=True)
    notes = fields.Text(string='Notes')

    @api.depends('date_required', 'state')
    def _compute_is_overdue(self):
        today = fields.Date.context_today(self)
        for rec in self:
            rec.is_overdue = (
                rec.date_required
                and rec.date_required < today
                and rec.state not in ('approved', 'na', 'received')
            )

    def action_send_document(self):
        """Open email composer with document attachments pre-loaded."""
        self.ensure_one()
        ship = self.shipment_id
        partner_ids = []
        if self.doc_source in ('generated', 'odoo_ref'):
            # Sending to client or broker
            if ship.partner_id:
                partner_ids.append(ship.partner_id.id)
        else:
            # Sending to carrier/forwarder
            if ship.carrier_partner_id:
                partner_ids.append(ship.carrier_partner_id.id)

        attachment_ids = self.attachment_ids.ids if self.attachment_ids else []

        return {
            'type': 'ir.actions.act_window',
            'res_model': 'mail.compose.message',
            'views': [[False, 'form']],
            'view_mode': 'form',
            'target': 'new',
            'context': {
                'default_model': 'crfp.shipment',
                'default_res_ids': [ship.id],
                'default_partner_ids': partner_ids,
                'default_subject': '%s - %s - %s' % (
                    dict(self._fields['doc_type'].selection).get(self.doc_type, ''),
                    ship.name, self.reference or ''),
                'default_attachment_ids': attachment_ids,
                'default_composition_mode': 'comment',
            },
        }
