from odoo import models, fields, api
from odoo.exceptions import UserError


class CrfpShipment(models.Model):
    _name = 'crfp.shipment'
    _description = 'Export Shipment'
    _order = 'create_date desc'
    _inherit = ['mail.thread', 'mail.activity.mixin']

    name = fields.Char(string='Shipment Ref', readonly=True, default='New', copy=False)
    state = fields.Selection([
        ('draft', 'Draft'),
        ('confirmed', 'Confirmed'),
        ('in_preparation', 'In Preparation'),
        ('docs_pending', 'Docs Pending'),
        ('shipped', 'Shipped'),
        ('in_transit', 'In Transit'),
        ('arrived', 'Arrived'),
        ('delivered', 'Delivered'),
        ('closed', 'Closed'),
    ], string='Status', default='draft', tracking=True, index=True)

    # ── Commercial (references only, no modifications) ──
    sale_order_id = fields.Many2one('sale.order', string='Sale Order',
                                     help='The confirmed sale order for this shipment')
    partner_id = fields.Many2one('res.partner', string='Client', tracking=True)
    incoterm = fields.Selection([
        ('EXW', 'EXW'), ('FCA', 'FCA'), ('FOB', 'FOB'),
        ('CFR', 'CFR'), ('CIF', 'CIF'), ('CPT', 'CPT'),
        ('CIP', 'CIP'), ('DAP', 'DAP'), ('DDP', 'DDP'),
    ], string='Incoterm', tracking=True)

    # ── Invoices (reference only — Odoo generates these) ──
    proforma_invoice_id = fields.Many2one('account.move', string='Proforma Invoice',
                                           help='Reference to Odoo proforma. NOT generated by logistics.')
    commercial_invoice_id = fields.Many2one('account.move', string='Commercial Invoice',
                                             help='Reference to Odoo invoice. NOT generated by logistics.')

    # ── Logistics partners ──
    carrier_partner_id = fields.Many2one('res.partner', string='Carrier (Naviera)',
                                          tracking=True)
    forwarder_partner_id = fields.Many2one('res.partner', string='Forwarder',
                                            tracking=True)

    # ── Route ──
    port_origin_id = fields.Many2one('crfp.port', string='Port of Origin',
                                      default=lambda self: self._default_origin_port())
    port_destination_id = fields.Many2one('crfp.port', string='Port of Destination',
                                           tracking=True)
    container_type_id = fields.Many2one('crfp.container.type', string='Container Type')

    # ── Transport ──
    vessel_name = fields.Char(string='Vessel', tracking=True)
    voyage_number = fields.Char(string='Voyage')

    # ── Dates ──
    etd = fields.Date(string='ETD (Estimated Departure)', tracking=True)
    eta = fields.Date(string='ETA (Estimated Arrival)', tracking=True)
    atd = fields.Datetime(string='ATD (Actual Departure)', tracking=True)
    ata = fields.Datetime(string='ATA (Actual Arrival)', tracking=True)
    cutoff_date = fields.Datetime(string='Cutoff Date',
                                   help='Deadline to deliver cargo to terminal')

    # ── Future-ready (optional) ──
    consignee_id = fields.Many2one('res.partner', string='Consignee',
                                    help='Recipient of goods at destination (for BL)')
    notify_party_id = fields.Many2one('res.partner', string='Notify Party',
                                       help='Party to notify at destination (for BL)')

    # ── Management ──
    responsible_id = fields.Many2one('res.users', string='Responsible',
                                      default=lambda self: self.env.user, tracking=True)
    notes = fields.Html(string='Notes')

    # ── One2many relations ──
    line_ids = fields.One2many('crfp.shipment.line', 'shipment_id', string='Shipment Lines')
    container_ids = fields.One2many('crfp.shipment.container', 'shipment_id', string='Containers')
    booking_id = fields.Many2one('crfp.shipment.booking', string='Booking')
    document_ids = fields.One2many('crfp.shipment.document', 'shipment_id', string='Documents')
    checklist_ids = fields.One2many('crfp.shipment.checklist', 'shipment_id', string='Checklist')
    alert_ids = fields.One2many('crfp.shipment.alert', 'shipment_id', string='Alerts')
    log_ids = fields.One2many('crfp.shipment.log', 'shipment_id', string='Communication Log')
    tracking_event_ids = fields.One2many('crfp.tracking.event', 'shipment_id', string='Tracking Events')

    # ── Computed totals ──
    total_boxes_planned = fields.Integer(compute='_compute_totals', store=True)
    total_boxes_actual = fields.Integer(compute='_compute_totals', store=True)
    total_pallets_planned = fields.Integer(compute='_compute_totals', store=True)
    total_pallets_actual = fields.Integer(compute='_compute_totals', store=True)
    total_net_weight_actual = fields.Float(compute='_compute_totals', store=True,
                                            digits=(12, 2))
    total_gross_weight_actual = fields.Float(compute='_compute_totals', store=True,
                                              digits=(12, 2))
    has_shortages = fields.Boolean(compute='_compute_totals', store=True)
    line_count = fields.Integer(compute='_compute_totals')

    docs_complete = fields.Boolean(compute='_compute_docs_progress')
    docs_pending_count = fields.Integer(compute='_compute_docs_progress')
    checklist_progress = fields.Float(compute='_compute_checklist_progress')
    alert_count = fields.Integer(compute='_compute_alert_count')

    @api.depends('line_ids.boxes_planned', 'line_ids.boxes_actual',
                 'line_ids.pallets_planned', 'line_ids.pallets_actual',
                 'line_ids.net_weight_actual', 'line_ids.gross_weight_actual',
                 'line_ids.has_shortage')
    def _compute_totals(self):
        for rec in self:
            lines = rec.line_ids
            rec.total_boxes_planned = sum(l.boxes_planned for l in lines)
            rec.total_boxes_actual = sum(l.boxes_actual for l in lines)
            rec.total_pallets_planned = sum(l.pallets_planned for l in lines)
            rec.total_pallets_actual = sum(l.pallets_actual for l in lines)
            rec.total_net_weight_actual = sum(l.net_weight_actual for l in lines)
            rec.total_gross_weight_actual = sum(l.gross_weight_actual for l in lines)
            rec.has_shortages = any(l.has_shortage for l in lines)
            rec.line_count = len(lines)

    @api.depends('document_ids.state', 'document_ids.is_required')
    def _compute_docs_progress(self):
        for rec in self:
            required = rec.document_ids.filtered(lambda d: d.is_required)
            done = required.filtered(lambda d: d.state in ('approved', 'na'))
            rec.docs_pending_count = len(required) - len(done)
            rec.docs_complete = len(required) == len(done) if required else False

    @api.depends('checklist_ids.state')
    def _compute_checklist_progress(self):
        for rec in self:
            total = len(rec.checklist_ids)
            done = len(rec.checklist_ids.filtered(lambda c: c.state in ('done', 'na')))
            rec.checklist_progress = (done / total * 100) if total else 0

    @api.depends('alert_ids.is_resolved')
    def _compute_alert_count(self):
        for rec in self:
            rec.alert_count = len(rec.alert_ids.filtered(lambda a: not a.is_resolved))

    def _default_origin_port(self):
        """Default origin port: Puerto Moin (Costa Rica)."""
        port = self.env['crfp.port'].search([('code', '=', 'MOI')], limit=1)
        return port.id if port else False

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get('name', 'New') == 'New':
                vals['name'] = self.env['ir.sequence'].next_by_code('crfp.shipment') or 'New'
        return super().create(vals_list)

    # ── Actions ──

    def action_load_from_sale_order(self):
        """Copy lines from sale.order into shipment lines as planned quantities."""
        self.ensure_one()
        if not self.sale_order_id:
            raise UserError('Please select a Sale Order first.')
        if self.line_ids:
            raise UserError('Shipment already has lines. Clear them first or create a new shipment.')

        so = self.sale_order_id
        # Set header fields from SO
        if not self.partner_id:
            self.partner_id = so.partner_id
        if not self.port_destination_id and hasattr(so, 'note') and so.note:
            # Try to find port from SO notes (set by crfp_pricing)
            pass

        for sol in so.order_line:
            if not sol.product_id:
                continue
            # Find matching crfp.product
            crfp_prod = self.env['crfp.product'].search([
                ('product_id', '=', sol.product_id.id)
            ], limit=1)

            qty = int(sol.product_uom_qty)
            net_kg = crfp_prod.net_kg if crfp_prod else 0
            bpp = 66  # default
            if crfp_prod:
                # Get boxes per pallet from pallet config
                pallet_cfg = self.env['crfp.pallet.config'].search([
                    ('product_keyword', 'ilike', crfp_prod.name.split()[0]),
                ], limit=1)
                if pallet_cfg:
                    bpp = pallet_cfg.boxes_per_pallet

            pallets = qty // bpp if bpp else 0

            self.env['crfp.shipment.line'].create({
                'shipment_id': self.id,
                'sale_order_line_id': sol.id,
                'product_id': sol.product_id.id,
                'crfp_product_id': crfp_prod.id if crfp_prod else False,
                'boxes_planned': qty,
                'pallets_planned': pallets,
                'boxes_per_pallet_planned': bpp,
                'net_weight_planned': qty * net_kg,
                'gross_weight_planned': qty * net_kg * 1.05,  # ~5% tare estimate
                'price_unit_planned': sol.price_unit,
            })

    def action_load_checklist_template(self):
        """Load checklist items from a template."""
        self.ensure_one()
        templates = self.env['crfp.checklist.template'].search([])
        if not templates:
            raise UserError('No checklist templates defined. Go to Configuration > Checklist Templates.')
        # Use first matching template (or let user pick via wizard in future)
        template = templates[0]
        for line in template.line_ids:
            self.env['crfp.shipment.checklist'].create({
                'shipment_id': self.id,
                'name': line.name,
                'sequence': line.sequence,
                'category': line.category,
                'is_blocking': line.is_blocking,
                'responsible_id': self.responsible_id.id,
            })

    def action_generate_packing_list(self):
        """Generate packing list PDF from actual quantities."""
        self.ensure_one()
        return self.env.ref('crfp_logistics.action_report_packing_list').report_action(self)

    def action_confirm(self):
        self.write({'state': 'confirmed'})

    def action_start_preparation(self):
        self.write({'state': 'in_preparation'})

    def action_docs_pending(self):
        self.write({'state': 'docs_pending'})

    def action_ship(self):
        self.write({'state': 'shipped', 'atd': fields.Datetime.now()})

    def action_in_transit(self):
        self.write({'state': 'in_transit'})

    def action_arrived(self):
        self.write({'state': 'arrived', 'ata': fields.Datetime.now()})

    def action_delivered(self):
        self.write({'state': 'delivered'})

    def action_close(self):
        self.write({'state': 'closed'})

    @api.model
    def _cron_generate_alerts(self):
        """Daily cron: generate alerts for active shipments."""
        today = fields.Date.context_today(self)
        now = fields.Datetime.now()
        Alert = self.env['crfp.shipment.alert']

        active_shipments = self.search([
            ('state', 'not in', ('closed', 'delivered', 'draft')),
        ])
        for ship in active_shipments:
            # Alert: overdue documents
            for doc in ship.document_ids:
                if doc.is_overdue and doc.is_required:
                    existing = Alert.search([
                        ('shipment_id', '=', ship.id),
                        ('alert_type', '=', 'document'),
                        ('message', 'ilike', doc.doc_type),
                        ('is_resolved', '=', False),
                    ], limit=1)
                    if not existing:
                        Alert.create({
                            'shipment_id': ship.id,
                            'alert_type': 'document',
                            'severity': 'critical',
                            'message': f'Document OVERDUE: {doc.doc_type} — deadline was {doc.date_required}',
                            'auto_generated': True,
                        })

            # Alert: cutoff approaching (48h)
            if ship.cutoff_date and not ship.atd:
                from datetime import timedelta
                if ship.cutoff_date <= now + timedelta(hours=48):
                    existing = Alert.search([
                        ('shipment_id', '=', ship.id),
                        ('alert_type', '=', 'deadline'),
                        ('message', 'ilike', 'cutoff'),
                        ('is_resolved', '=', False),
                    ], limit=1)
                    if not existing:
                        Alert.create({
                            'shipment_id': ship.id,
                            'alert_type': 'deadline',
                            'severity': 'warning',
                            'message': f'Cutoff date approaching: {ship.cutoff_date}',
                            'auto_generated': True,
                        })
