from odoo import models, fields

class CrfpDocumentType(models.Model):
    _name = 'crfp.document.type'
    _description = 'Shipment Document Type'
    _order = 'sequence, name'

    name = fields.Char(string='Name', required=True)
    code = fields.Char(string='Code', required=True, help='Technical code e.g. booking_request')
    default_source = fields.Selection([
        ('generated', 'Generated by us'),
        ('received', 'Received from third party'),
        ('odoo_ref', 'Odoo reference document'),
        ('control', 'Control only'),
    ], string='Default Source', default='received')
    is_required_default = fields.Boolean(string='Required by Default', default=True)
    applies_to_europe = fields.Boolean(string='Only for Europe', default=False)
    applies_to_incoterms = fields.Char(string='Only for Incoterms', help='Comma-separated list e.g. CIF,CIP,DAP,DDP')
    sequence = fields.Integer(default=10)
    active = fields.Boolean(default=True)

    code_unique = models.Constraint(
        'UNIQUE(code)',
        'Document type code must be unique.',
    )
